export { default as Hero } from "./Hero"
export { default as Problems } from "./Problems"
export { default as Ideais } from "./Ideais"
export { default as NextStep } from "./NextStep"
export { default as Contact } from "./Contact"